# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
