# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20161206_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
