# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_group_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupId',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='groupName',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='group',
            name='groupcreateId',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='groupuserId',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='trans',
            name='groupId',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='trans',
            name='tansName',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='trans',
            name='transId',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='trans',
            name='transamount',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='trans',
            name='transuserId',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
