# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20161207_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans',
            name='transId',
        ),
    ]
