# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_remove_appgroup_groupid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appgroup',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='trans',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='usertable',
            options={'ordering': ('created',)},
        ),
    ]
